$(document).ready(function () {
    var oshoBooks = [
        {
            "srno": "1",
            "ImageURL": "https://images-na.ssl-images-amazon.com/images/I/41944poouzL._SX347_BO1,204,203,200_.jpg",
            "EnglishBookTitleName": "Compendium On Osho Dynamic Meditation (Pb)",
            "Publication": "Osho Media",
            "Subject": "Guides To Meditation",
            "Cover": "PB",
            "MAX": "MRP &#8377;",
            "MRP": "900",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "720",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        },
        {
            "srno": "2",
            "ImageURL": "bookImages/med.webp",
            "EnglishBookTitleName": "Meditation: Art of Ecstasy",
            "Publication": "Osho Media International",
            "Subject": "Guides To Meditation",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "775",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "620",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        },
        {
            "srno": "3",
            "ImageURL": "https://images-na.ssl-images-amazon.com/images/I/41vs03E+6JL._SY344_BO1,204,203,200_.jpg",
            "EnglishBookTitleName": "Meditation: First & Last Freedom",
            "Publication": "Osho Media International",
            "Subject": "Guides To Meditation",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "625",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "500",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        },
        {
            "srno": "4",
            "ImageURL": "bookImages/med2.jpg",
            "EnglishBookTitleName": "Osho Meditation Inc.",
            "Publication": "Osho Media International",
            "Subject": "Guides To Meditation",
            "Cover": "PB",
            "MAX": "MRP &#8377;",
            "MRP": "375",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "300",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        },
        {
            "srno": "5",
            "ImageURL": "bookImages/new.webp",
            "EnglishBookTitleName": "NEW ALCHEMY TO TURN YOU ON, THE",
            "Publication": "Osho Media International",
            "Subject": "Guides To Meditation",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "500",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "400",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        },
        {
            "srno": "6",
            "ImageURL": "https://images-na.ssl-images-amazon.com/images/I/517GOwByStL._SX333_BO1,204,203,200_.jpg",
            "EnglishBookTitleName": "Osho Zen Tarot",
            "Publication": "Osho Media International",
            "Subject": "Guides To Meditation",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "1500",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "1000",
            "Discount": "33.3333333333333% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": ""
        },
        {
            "srno": "7",
            "ImageURL": "bookImages/perfect.jpg",
            "EnglishBookTitleName": "Perfect Way",
            "Publication": "Osho Media International",
            "Subject": "Guides To Meditation",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "600",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "480",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "60"
        },
        {
            "srno": "8",
            "ImageURL": "bookImages/now.webp",
            "EnglishBookTitleName": "And Now And Here",
            "Publication": "Osho Media International",
            "Subject": "The Science of Inner",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "1500",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "1200",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "150"
        },
        {
            "srno": "9",
            "ImageURL": "bookImages/astro.webp",
            "EnglishBookTitleName": "Astrology",
            "Publication": "Osho Media International",
            "Subject": "The Science of Inner",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "375",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "300",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "60"
        },
        {
            "srno": "10",
            "ImageURL": "https://images-na.ssl-images-amazon.com/images/I/41262+R2eSL._SX308_BO1,204,203,200_.jpg",
            "EnglishBookTitleName": "Breaking All Boundaries",
            "Publication": "Osho Media International",
            "Subject": "The Science of Inner",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "375",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "300",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "60"
        },
        {
            "srno": "11",
            "ImageURL": "bookImages/com.webp",
            "EnglishBookTitleName": "Compassion & Revolution",
            "Publication": "Osho Media International",
            "Subject": "The Science of Inner",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "500",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "400",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        },
        {
            "srno": "12",
            "ImageURL": "bookImages/eternal.webp",
            "EnglishBookTitleName": "Eternal Quest",
            "Publication": "Osho Media International",
            "Subject": "Responses To Questions",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "575",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "460",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "60"
        },
        {
            "srno": "13",
            "ImageURL": "bookImages/falling.webp",
            "EnglishBookTitleName": "Falling In Love with Darkness",
            "Publication": "Osho Media International",
            "Subject": "The Science of Inner",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "600",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "480",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        },
        {
            "srno": "14",
            "ImageURL": "https://images-na.ssl-images-amazon.com/images/I/51NcnOaf+GL._SX258_BO1,204,203,200_.jpg",
            "EnglishBookTitleName": "From Sex To Superconsciousness",
            "Publication": "Osho Media International",
            "Subject": "The Science of Inner",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "525",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "420",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "60"
        },
        {
            "srno": "15",
            "ImageURL": "https://images-na.ssl-images-amazon.com/images/I/41092X8qgEL._SX348_BO1,204,203,200_.jpg",
            "EnglishBookTitleName": "Hidden Mystries",
            "Publication": "Osho Media International",
            "Subject": "The Science of Inner",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "500",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "400",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "60"
        },
        {
            "srno": "16",
            "ImageURL": "bookImages/search.webp",
            "EnglishBookTitleName": "In Search of Miraculous",
            "Publication": "Osho Media International",
            "Subject": "The Science of Inner",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "1425",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "1140",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        },
        {
            "srno": "17",
            "ImageURL": "bookImages/mind.webp",
            "EnglishBookTitleName": "Independent Mind",
            "Publication": "Osho Media International",
            "Subject": "The Science of Inner",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "425",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "340",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "60"
        },
        {
            "srno": "18",
            "ImageURL": "bookImages/void.webp",
            "EnglishBookTitleName": "INTO THE VOID",
            "Publication": "Osho Media International",
            "Subject": "The Science of Inner",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "425",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "340",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "60"
        },
        {
            "srno": "19",
            "ImageURL": "https://images-na.ssl-images-amazon.com/images/I/31s5B3lFrQL._SX310_BO1,204,203,200_.jpg",
            "EnglishBookTitleName": "Key To A New Life",
            "Publication": "Osho Media International",
            "Subject": "The Science of Inner",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "550",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "440",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "60"
        },
        {
            "srno": "20",
            "ImageURL": "bookImages/eso.webp",
            "EnglishBookTitleName": "PSYCHOLOGY OF THE ESOTERIC",
            "Publication": "Osho Media International",
            "Subject": "The Science of Inner",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "800",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "640",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        },
        {
            "srno": "21",
            "ImageURL": "bookImages/date.webp",
            "EnglishBookTitleName": "RELIGIONS EXPIRATION DATE",
            "Publication": "Osho Media International",
            "Subject": "The Science of Inner",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "525",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "420",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        },
        {
            "srno": "22",
            "ImageURL": "bookImages/peace.webp",
            "EnglishBookTitleName": "SEARCH FOR PEACE",
            "Publication": "Osho Media International",
            "Subject": "The Science of Inner",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "450",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "360",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "60"
        },
        {
            "srno": "23",
            "ImageURL": "https://images-na.ssl-images-amazon.com/images/I/11QA6+Jn4DL._BO1,204,203,200_.jpg",
            "EnglishBookTitleName": "Silence: the Message of Your Being",
            "Publication": "Osho Media International",
            "Subject": "The Science of Inner",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "550",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "440",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        },
        {
            "srno": "24",
            "ImageURL": "bookImages/steps.webp",
            "EnglishBookTitleName": "Three Steps to Awakening",
            "Publication": "Osho Media International",
            "Subject": "The Science of Inner",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "325",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "260",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "60"
        },
        {
            "srno": "25",
            "ImageURL": "bookImages/tea.webp",
            "EnglishBookTitleName": "Cup of Tea A",
            "Publication": "Osho Media International",
            "Subject": "Published Letters",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "375",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "300",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "60"
        },
        {
            "srno": "26",
            "ImageURL": "https://images-na.ssl-images-amazon.com/images/I/41iMiIS+f3L._SX258_BO1,204,203,200_.jpg",
            "EnglishBookTitleName": "Earthen Lamps",
            "Publication": "Osho Media International",
            "Subject": "Published Letters",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "850",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "680",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        },
        {
            "srno": "27",
            "ImageURL": "bookImages/love.webp",
            "EnglishBookTitleName": "Flowers Of Love",
            "Publication": "Osho Media International",
            "Subject": "Published Letters",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "325",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "260",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "60"
        },
        {
            "srno": "28",
            "ImageURL": "bookImages/soap.webp",
            "EnglishBookTitleName": "Life Is A Soup Bubble",
            "Publication": "Osho Media International",
            "Subject": "Published Letters",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "625",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "500",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        },
        {
            "srno": "29",
            "ImageURL": "bookImages/letter.webp",
            "EnglishBookTitleName": "Love Letters to Life",
            "Publication": "Osho Media International",
            "Subject": "Published Letters",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "325",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "260",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "60"
        },
        {
            "srno": "30",
            "ImageURL": "https://images-na.ssl-images-amazon.com/images/I/41ibOC+rB9L._SX258_BO1,204,203,200_.jpg",
            "EnglishBookTitleName": "Books I Have Loved",
            "Publication": "Osho Media International",
            "Subject": "Autobiographic",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "2250",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "1800",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "150"
        },
        {
            "srno": "31",
            "ImageURL": "bookImages/glimpe.webp",
            "EnglishBookTitleName": "Glimpses of A Golden Childhood",
            "Publication": "Osho Media International",
            "Subject": "Autobiographic",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "1375",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "1100",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "120"
        },
        {
            "srno": "32",
            "ImageURL": "https://images-na.ssl-images-amazon.com/images/I/419+xN6JFHL._SX258_BO1,204,203,200_.jpg",
            "EnglishBookTitleName": "Notes of a Madman",
            "Publication": "Osho Media International",
            "Subject": "Autobiographic",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "425",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "340",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "60"
        },
        {
            "srno": "33",
            "ImageURL": "bookImages/above.webp",
            "EnglishBookTitleName": "Above All Don�t Wobble",
            "Publication": "Osho Media International",
            "Subject": "One -To- One Talks",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "900",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "720",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        }
,
        {
            "srno": "34",
            "ImageURL": "bookImages/hammer.webp",
            "EnglishBookTitleName": "Hammer On the Rock",
            "Publication": "Osho Media International",
            "Subject": "One -To- One Talks",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "675",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "540",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        },
        {
            "srno": "35",
            "ImageURL": "bookImages/beyond.webp",
            "EnglishBookTitleName": "Beyond Enlightenment",
            "Publication": "Osho Media International",
            "Subject": "Responses To Questions",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "775",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "620",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        },
        {
            "srno": "36",
            "ImageURL": "bookImages/come.webp",
            "EnglishBookTitleName": "COME, COME, YET AGAIN COME",
            "Publication": "Osho Media International",
            "Subject": "Responses To Questions",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "475",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "380",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        },
        {
            "srno": "37",
            "ImageURL": "bookImages/unknown.webp",
            "EnglishBookTitleName": "From Uncounciousness To Counciousness",
            "Publication": "Osho Media International",
            "Subject": "Respnses to Questions",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "1625",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "1235",
            "Discount": "24% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "120"
        },
        {
            "srno": "38",
            "ImageURL": "bookImages/myway",
            "EnglishBookTitleName": "MY WAY: WAY OF THE WHITE CLOUDS",
            "Publication": "Osho Media International",
            "Subject": "Responses To Questions",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "875",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "700",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        },
        {
            "srno": "39",
            "ImageURL": "bookImages/mystci.webp",
            "EnglishBookTitleName": "Path Of Mystic",
            "Publication": "Osho Media International",
            "Subject": "Responses To Questions",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "1600",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "1120",
            "Discount": "30% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "120"
        },
        {
            "srno": "40",
            "ImageURL": "bookImages/spirit.webp",
            "EnglishBookTitleName": "Rebellious Spirit",
            "Publication": "Osho Media International",
            "Subject": "Responses To Questions",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "1000",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "800",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        },
        {
            "srno": "41",
            "ImageURL": "bookImages/sermons.webp",
            "EnglishBookTitleName": "Sermons In Stones",
            "Publication": "Osho Media International",
            "Subject": "Respnses to Questions",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "1500",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "1200",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "120"
        },
        {
            "srno": "42",
            "ImageURL": "bookImages/wild.webp",
            "EnglishBookTitleName": "The Wild Geese And The Water",
            "Publication": "Osho Media International",
            "Subject": "Respnses to Questions",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "800",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "640",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        },
        {
            "srno": "43",
            "ImageURL": "bookImages/zen.webp",
            "EnglishBookTitleName": "ZEN: ZEST, ZIP, ZAP AND ZING",
            "Publication": "Osho Media International",
            "Subject": "Responses To Questions",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "900",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "720",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        },
        {
            "srno": "44",
            "ImageURL": "bookImages/book.webp",
            "EnglishBookTitleName": "Book of Secrets",
            "Publication": "Osho Media International",
            "Subject": "Tantra Masters",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "1500",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "1050",
            "Discount": "30% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "120"
        },
        {
            "srno": "45",
            "ImageURL": "bookImages/ex.webp",
            "EnglishBookTitleName": "TANTRA EXPERIENCE",
            "Publication": "Osho Media International",
            "Subject": "Tantra Masters",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "725",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "580",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        },
        {
            "srno": "46",
            "ImageURL": "bookImages/tantric.webp",
            "EnglishBookTitleName": "TANTRIC TRANSFORMATION",
            "Publication": "Osho Media International",
            "Subject": "Tantra Masters",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "750",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "600",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        },
        {
            "srno": "47",
            "ImageURL": "bookImages/hsin.webp",
            "EnglishBookTitleName": "HSIN HSIN MING: THE BOOK OF NOTHING",
            "Publication": "Osho Media International",
            "Subject": "Tao Masters",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "625",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "600",
            "Discount": "4% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        },
        {
            "srno": "48",
            "ImageURL": "bookImages/sec.webp",
            "EnglishBookTitleName": "SECRET OF SECRETS",
            "Publication": "Osho Media International",
            "Subject": "Tao Masters",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "2250",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "1500",
            "Discount": "33.3333333333333% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "120"
        },
        {
            "srno": "49",
            "ImageURL": "bookImages/thesearch.webp",
            "EnglishBookTitleName": "SEARCH",
            "Publication": "Osho Media International",
            "Subject": "Tao Masters",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "600",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "480",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        },
        {
            "srno": "50",
            "ImageURL": "bookImages/pyar.webp",
            "EnglishBookTitleName": "WORK IS LOVE MADE VISIBLE",
            "Publication": "Osho Media International",
            "Subject": "Vision For The World",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "675",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "540",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        },
        {
            "srno": "51",
            "ImageURL": "bookImages/yoga.webp",
            "EnglishBookTitleName": "Path of Yoga (Vol.01)",
            "Publication": "Osho Media International",
            "Subject": "Yoga: Science of soul Series",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "1050",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "840",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        },
        {
            "srno": "52",
            "ImageURL": "bookImages/heart.webp",
            "EnglishBookTitleName": "HEART OF YOGA (VOL.02)",
            "Publication": "Osho Media International",
            "Subject": "Yoga: Science of soul Series",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "625",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "500",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        },
        {
            "srno": "53",
            "ImageURL": "mystery.webp",
            "EnglishBookTitleName": "Yoga: Mystery beyond Mind (Vol. 03)",
            "Publication": "Osho Media International",
            "Subject": "Yoga: Science of soul Series",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "800",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "640",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        },
        {
            "srno": "54",
            "ImageURL": "https://images-na.ssl-images-amazon.com/images/I/41AQDfhUUPL._SX323_BO1,204,203,200_.jpg",
            "EnglishBookTitleName": "ALCHEMY OF YOGA (VOL.4)",
            "Publication": "Osho Media International",
            "Subject": "Yoga: Science of soul Series",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "575",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "460",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        },
        {
            "srno": "55",
            "ImageURL": "bookImages/bodhi.webp",
            "EnglishBookTitleName": "BODHIDHARMA:THE GREATEST ZEN MASTER",
            "Publication": "Osho Media International",
            "Subject": "Buddha & Buddhist Master",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "1075",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "860",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        },
        {
            "srno": "56",
            "ImageURL": "bookImages/sutra.webp",
            "EnglishBookTitleName": "Heart Sutra",
            "Publication": "Osho Media International",
            "Subject": "Buddha & Buddhist Master",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "1000",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "800",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        },
        {
            "srno": "57",
            "ImageURL": "bookImages/ownway.webp",
            "EnglishBookTitleName": "Finding Your Own Way (Discipline of Transcendence-1)",
            "Publication": "Osho Media International",
            "Subject": "Buddha & Buddhist Master",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "850",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "680",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        },
        {
            "srno": "58",
            "ImageURL": "bookImages/into.webp",
            "EnglishBookTitleName": "Moving In To The Known(Discipline of Transcendence-II)",
            "Publication": "Osho Media International",
            "Subject": "Buddha & Buddhist Master",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "850",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "680",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        },
        {
            "srno": "59",
            "ImageURL": "bookImages/happy.webp",
            "EnglishBookTitleName": "Learning Happiness (Discipline of Transcendence - III)",
            "Publication": "Osho Media International",
            "Subject": "Buddha & Buddhist Master",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "700",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "560",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        },
        {
            "srno": "60",
            "ImageURL": "bookImages/dancing.webp",
            "EnglishBookTitleName": "Dancing in the Breeze (Discipline of Transcendence - IV)",
            "Publication": "Osho Media International",
            "Subject": "Buddha & Buddhist Master",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "900",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "720",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        },
        {
            "srno": "61",
            "ImageURL": "https://images-na.ssl-images-amazon.com/images/I/41p17kjfPoL._SY351_BO1,204,203,200_.jpg",
            "EnglishBookTitleName": "Isan : No Foot Prints In Th Blue Sky",
            "Publication": "Osho Media International",
            "Subject": "Zen masters",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "575",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "460",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "60"
        },
        {
            "srno": "62",
            "ImageURL": "https://images-na.ssl-images-amazon.com/images/I/31bEEAgsiHL._SX234_BO1,204,203,200_.jpg",
            "EnglishBookTitleName": "JOSHU THE LION'S ROAR: ZEN",
            "Publication": "Osho Media International",
            "Subject": "Zen Master",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "750",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "600",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "60"
        },
        {
            "srno": "63",
            "ImageURL": "bookImages/matzu.webp",
            "EnglishBookTitleName": "MA TZU THE EMPTY MIRROR",
            "Publication": "Osho Media International",
            "Subject": "zen Masters",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "500",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "400",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "60"
        },
        {
            "srno": "64",
            "ImageURL": "bookImages/yakusan.webp",
            "EnglishBookTitleName": "YAKUSAN:STRAIGHT TO THE POINT",
            "Publication": "Osho Media International",
            "Subject": "Zen Master",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "750",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "600",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "60"
        },
        {
            "srno": "65",
            "ImageURL": "https://images-na.ssl-images-amazon.com/images/I/3100Rl5kAzL._SX308_BO1,204,203,200_.jpg",
            "EnglishBookTitleName": "AH, THIS",
            "Publication": "Osho Media International",
            "Subject": "zen Masters",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "475",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "380",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "60"
        },
        {
            "srno": "66",
            "ImageURL": "bookImages/grass.webp",
            "EnglishBookTitleName": "And The Grass Grows By Itself",
            "Publication": "Osho Media International",
            "Subject": "zen Masters",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "975",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "780",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "60"
        },
        {
            "srno": "67",
            "ImageURL": "bookImages/livezen.webp",
            "EnglishBookTitleName": "LIVE ZEN",
            "Publication": "Osho Media International",
            "Subject": "zen Masters",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "975",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "780",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        },
        {
            "srno": "68",
            "ImageURL": "bookImages/take.webp",
            "EnglishBookTitleName": "Take It Easy",
            "Publication": "Osho Media International",
            "Subject": "zen Masters",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "1050",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "840",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "120"
        },
        {
            "srno": "69",
            "ImageURL": "bookImages/sitting.webp",
            "EnglishBookTitleName": "Walking In Zen sitting in Zen",
            "Publication": "Osho Media International",
            "Subject": "zen Masters",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "1500",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "1200",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        },
        {
            "srno": "70",
            "ImageURL": "bookImages/yahoo.webp",
            "EnglishBookTitleName": "YAA-HOO THE MYSTIC ROSE",
            "Publication": "Osho Media International",
            "Subject": "zen Masters",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "1000",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "800",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        },
        {
            "srno": "71",
            "ImageURL": "bookImages/zenma.webp",
            "EnglishBookTitleName": "ZEN MANIFESTO",
            "Publication": "Osho Media International",
            "Subject": "Zen Talks",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "925",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "740",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        },
        {
            "srno": "72",
            "ImageURL": "bookImages/say.webp",
            "EnglishBookTitleName": "I say Unto You Vol.1",
            "Publication": "Osho Media International",
            "Subject": "Jesus and Christian Mystics",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "625",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "500",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        },
        {
            "srno": "73",
            "ImageURL": "bookImages/guida.webp",
            "EnglishBookTitleName": "GUIDA SPIRITUALE",
            "Publication": "Osho Media International",
            "Subject": "Western Mystics",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "700",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "560",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        },
        {
            "srno": "74",
            "ImageURL": "bookImages/hidden.webp",
            "EnglishBookTitleName": "THE HIDDEN HARMONY",
            "Publication": "Osho Media International",
            "Subject": "Western Mystics",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "750",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "600",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        },
        {
            "srno": "75",
            "ImageURL": "bookImages/vol1.webp",
            "EnglishBookTitleName": "PHILOSOPHIA PERENNIS VOL 01",
            "Publication": "Osho Media International",
            "Subject": "Western Mystics",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "625",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "500",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        },
        {
            "srno": "76",
            "ImageURL": "bookImages/vol2.webp",
            "EnglishBookTitleName": "PHILOSOPHIA PERENNIS VOL 02",
            "Publication": "Osho Media International",
            "Subject": "Western Mystics",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "700",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "560",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        },
        {
            "srno": "77",
            "ImageURL": "bookImages/prophet.webp",
            "EnglishBookTitleName": "REFLECTIONS ON KAHLIL GIBRANS THE PROPHET",
            "Publication": "Osho Media International",
            "Subject": "Western Mystics",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "975",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "780",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        },
        {
            "srno": "78",
            "ImageURL": "https://images-na.ssl-images-amazon.com/images/I/51oDNGV1UpL._SX338_BO1,204,203,200_.jpg",
            "EnglishBookTitleName": "ZARATHUSTRA:LAUGHING PROPHET",
            "Publication": "Osho Media International",
            "Subject": "On Neitzsche's Thus Spake Zarathustra",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "750",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "600",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        },
        {
            "srno": "79",
            "ImageURL": "bookImages/zara.webp",
            "EnglishBookTitleName": "ZARATHUSTRA:GOD THAT CAN DANCE",
            "Publication": "Osho Media International",
            "Subject": "On Neitzsche's Thus Spake Zarathustra",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "650",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "520",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        },
        {
            "srno": "80",
            "ImageURL": "https://images-na.ssl-images-amazon.com/images/I/51ffKoNrWhL._SX334_BO1,204,203,200_.jpg",
            "EnglishBookTitleName": "BLISS:LIVING BEYOND HAPPINESS AND MISERY",
            "Publication": "Osho Media International",
            "Subject": "Indian Mystics (Shiva)",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "1250",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "1000",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        },
        {
            "srno": "81",
            "ImageURL": "bookImages/etc.webp",
            "EnglishBookTitleName": "Ecstasy: The Forgotten Language",
            "Publication": "Osho Media International",
            "Subject": "Indian Mystics (Kabir)",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "975",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "780",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        },
        {
            "srno": "82",
            "ImageURL": "bookImages/divine.webp",
            "EnglishBookTitleName": "The DIVINE MELODY",
            "Publication": "Osho Media International",
            "Subject": "Indian Mystics (Kabir)",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "650",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "520",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        },
        {
            "srno": "83",
            "ImageURL": "https://images-na.ssl-images-amazon.com/images/I/312nTFizi9L._SX336_BO1,204,203,200_.jpg",
            "EnglishBookTitleName": "Path of Love",
            "Publication": "Osho Media International",
            "Subject": "Indian Mystics (Kabir)",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "750",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "600",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        },
        {
            "srno": "84",
            "ImageURL": "https://images-na.ssl-images-amazon.com/images/I/41js0CXl+JL._SY344_BO1,204,203,200_.jpg",
            "EnglishBookTitleName": "VEDANTA :SEVEN STEPS TO SAMADHI",
            "Publication": "Osho Media International",
            "Subject": "Upanishad",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "1425",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "1140",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "120"
        },
        {
            "srno": "85",
            "ImageURL": "bookImages/random.webp",
            "EnglishBookTitleName": "RANDOM THOUGHTS",
            "Publication": "Osho Media International",
            "Subject": "Published Letters",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "875",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "700",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        },
        {
            "srno": "86",
            "ImageURL": "bookImages/goose.webp",
            "EnglishBookTitleName": "GOOSE IS OUT",
            "Publication": "Osho Media International",
            "Subject": "Responses To Questions",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "650",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "520",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        },
        {
            "srno": "87",
            "ImageURL": "bookImages/ancient.webp",
            "EnglishBookTitleName": "ANCIENT MUSIC IN THE PINES",
            "Publication": "Osho Media International",
            "Subject": "Zen Talks",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "1250",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "900",
            "Discount": "28% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        },
        {
            "srno": "88",
            "ImageURL": "bookImages/hyazen.webp",
            "EnglishBookTitleName": "HYAKUJO",
            "Publication": "Osho Media International",
            "Subject": "Zen masters",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "750",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "600",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        },
        {
            "srno": "89",
            "ImageURL": "bookImages/dawn.webp",
            "EnglishBookTitleName": "THE NEW DAWN",
            "Publication": "Osho Media International",
            "Subject": "Osho's vision for the world",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "1250",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "1000",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        },
        {
            "srno": "90",
            "ImageURL": "bookImages/up.webp",
            "EnglishBookTitleName": "Osho UPNISHAD",
            "Publication": "Osho Media International",
            "Subject": "The World Tour",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "2250",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "1800",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "150"
        },
        {
            "srno": "91",
            "ImageURL": "bookImages/being_osho.webp",
            "EnglishBookTitleName": "BEING OSHO",
            "Publication": "Zorba",
            "Subject": "DARSHAN DAIRY",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "750",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "600",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "0"
        },
        {
            "srno": "92",
            "ImageURL": "bookImages/ocean.webp",
            "EnglishBookTitleName": "CALL OF THE OCEAN",
            "Publication": "Zorba",
            "Subject": "AUTOBIOGRAPHIC",
            "Cover": "PB",
            "MAX": "MRP &#8377;",
            "MRP": "500",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "400",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "0"
        },
        {
            "srno": "93",
            "ImageURL": "bookImages/comdey.webp",
            "EnglishBookTitleName": "FROM TRAGEDY TO COMEDY",
            "Publication": "Zorba",
            "Subject": "MULLA NASRUDIN",
            "Cover": "PB",
            "MAX": "MRP &#8377;",
            "MRP": "250",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "200",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "60"
        },
        {
            "srno": "94",
            "ImageURL": "bookImages/story.webp",
            "EnglishBookTitleName": "AND THE FLOWER SHOWERED",
            "Publication": "Osho Media International",
            "Subject": "ZEN MASRERS",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "825",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "660",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        },
        {
            "srno": "95",
            "ImageURL": "bookImages/ultima.webp",
            "EnglishBookTitleName": "PHILOSOPHIA ULTIMA",
            "Publication": "Osho Media International",
            "Subject": "INDIA MYSTIC",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "825",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "660",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        },
        {
            "srno": "96",
            "ImageURL": "https://images-na.ssl-images-amazon.com/images/I/41t13Fti-CL._SX329_BO1,204,203,200_.jpg",
            "EnglishBookTitleName": "The Way Beyond Any Way",
            "Publication": "Osho Media International",
            "Subject": "UPNISHD",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "925",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "740",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        },
        {
            "srno": "97",
            "ImageURL": "bookImages/beyond.webp",
            "EnglishBookTitleName": "DIMENSION BEYOND UNKNOWN",
            "Publication": "Osho Media International",
            "Subject": "THE SCIENCE OF INNER",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "750",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "600",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        },
        {
            "srno": "98",
            "ImageURL": "bookImages/empty.webp",
            "EnglishBookTitleName": "EMPTY BOAT",
            "Publication": "Osho Media International",
            "Subject": "Tao Masters",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "800",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "640",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        },
        {
            "srno": "99",
            "ImageURL": "bookImages/running.webp",
            "EnglishBookTitleName": "AS IF A TREE STARTS RUNNING",
            "Publication": "Osho Media International",
            "Subject": "YAARI",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "1000",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "800",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        },
        {
            "srno": "100",
            "ImageURL": "bookImages/omsan.webp",
            "EnglishBookTitleName": "Om Shantih Shantih Shantih",
            "Publication": "Pan",
            "Subject": "mantra series",
            "Cover": "PB",
            "MAX": "MRP &#8377;",
            "MRP": "599",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "300",
            "Discount": "49.9165275459099% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        },
        {
            "srno": "101",
            "ImageURL": "https://m.media-amazon.com/images/I/51CCP7HjubL.jpg",
            "EnglishBookTitleName": "communism and zen fire zen wind",
            "Publication": "Osho Media International",
            "Subject": "zen msters",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "1000",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "750",
            "Discount": "25% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        },
        {
            "srno": "102",
            "ImageURL": "https://images-na.ssl-images-amazon.com/images/I/41nmH4MYrbL._SX316_BO1,204,203,200_.jpg",
            "EnglishBookTitleName": "ZenThe Mystery And Poetry Of The Beyond",
            "Publication": "Osho Media International",
            "Subject": "zen masters",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "1000",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "750",
            "Discount": "25% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        },
        {
            "srno": "103",
            "ImageURL": "bookImages/leap.webp",
            "EnglishBookTitleName": "ZenThe quantam Leap From Mind To Nomind",
            "Publication": "Osho Media International",
            "Subject": "zen masters",
            "Cover": "HB",
            "MAX": "MRP &#8377;",
            "MRP": "700",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "560",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        },
        {
            "srno": "104",
            "ImageURL": "bookImages/tou.webp",
            "EnglishBookTitleName": "Osho UPNISHAD",
            "Publication": "Diamond Pocket Books",
            "Subject": "The World Tour",
            "Cover": "PB",
            "MAX": "MRP &#8377;",
            "MRP": "595",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "476",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        },
        {
            "srno": "105",
            "ImageURL": "bookImages/enlight.webp",
            "EnglishBookTitleName": "Beyond Enlightenment",
            "Publication": "Diamond Pocket Books",
            "Subject": "Responses To Questions",
            "Cover": "PB",
            "MAX": "MRP &#8377;",
            "MRP": "495",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "396",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        },
        {
            "srno": "106",
            "ImageURL": "https://images-na.ssl-images-amazon.com/images/I/41g7sfUL+6L._SX331_BO1,204,203,200_.jpg",
            "EnglishBookTitleName": "Sermon In Stones",
            "Publication": "Diamond Pocket Books",
            "Subject": "Responses To Questions",
            "Cover": "PB",
            "MAX": "MRP &#8377;",
            "MRP": "495",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "396",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "90"
        },
        {
            "srno": "107",
            "ImageURL": "https://images-na.ssl-images-amazon.com/images/I/511N9YO9ebL._SX324_BO1,204,203,200_.jpg",
            "EnglishBookTitleName": "Gita Darshan vol.2",
            "Publication": "Full Circle",
            "Subject": "Krishna",
            "Cover": "PB",
            "MAX": "MRP &#8377;",
            "MRP": "499",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "400",
            "Discount": "19.8396793587174% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "60"
        },
        {
            "srno": "108",
            "ImageURL": "bookImages/education.webp",
            "EnglishBookTitleName": "Osho Vision On Education",
            "Publication": "Diamond Pocket Books",
            "Subject": "Vividh",
            "Cover": "PB",
            "MAX": "MRP &#8377;",
            "MRP": "250",
            "sell": "Sale Price &#8377;",
            "SALEPRICE": "200",
            "Discount": "20% OFF",
            "shipper": "Shippping Charge &#8377;",
            "SHIPPING": "60"
        }
];
    $("#kitabe").mirandajs(oshoBooks);

});
